### ISSUE TITLE
Ensure proper behaviour of new_version

### ISSUE THREAD

**Issue by alexbarcelo** [bsc-dom/pyclay#33]
The code of the new_version (in the ExecutionEnvironment.py) is implemented, but I suspect that it has not been tested for a long time (I may be mistaken). Or maybe it has never been executed at all.

We should check that it works as advised --as COMPSs will be using it in their applications.

**Comment by dgasull** [comment]
Seems to be working, I've created a test in https://github.com/bsc-dom/dataclay-demos/tree/new_version_demo/newversion-python that does the following:
- create object and registers it in a python app
- a java app creates the version using StorageItf
- python app gets the object by ID and executes __str__
