### ISSUE TITLE
Fix the serialization of volatile complex objects

### ISSUE THREAD

**Issue by alexbarcelo** [bsc-dom/pyclay#6]
We have been reported what seems to be a bug.

Rough steps in order to replicate the bug:
 - prepare a class A that contains (as attributes) an integer and a list
 - prepare a class B
 - add a method to the class B that expects an instance of the class A
 - register the model
 - create an instance of A --**do not make it persistent**
 - create an instance of B
 - make persistent the instance of B
 - call the method of the B instance

We would expect to work it without issues.

The reported bug showed that the list ended up in the `pending_obj` list, which is a serialization backlog for `serialize_params_or_return` which should only contain DataClayObject and thus the list should not be in there.

**Comment by dgasull** [comment]
@alexbarcelo check if it is still a bug or not and we check what to do.

**Comment by alexbarcelo** [comment]
I haven't been able to replicate this bug. Either it has been accidentally solved by the 2.1 release, or I missed something in the reproducibility steps.
